noestedmvc/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Noested.Data;
using Noested.Models;

namespace Noested.Controllers
{
    [Authorize(Roles="Admin, User")]
    public class CustomersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CustomersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Customers
        public async Task<IActionResult> Index()
        {
            return _context.Customer != null ?
                        View(await _context.Customer.ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.Customer'  is null.");
        }

        // GET: Customers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Customer == null)
            {
                return NotFound();
            }

            var customer = await _context.Customer
                .FirstOrDefaultAsync(m => m.CustomerId == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // GET: Customers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CustomerId,FirstName,LastName,Street,PostalCode,City,Email,Phone")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(customer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        // GET: Customers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Customer == null)
            {
                return NotFound();
            }

            var customer = await _context.Customer.FindAsync(id);
            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CustomerId,FirstName,LastName,Street,PostalCode,City,Email,Phone")] Customer customer)
        {
            if (id != customer.CustomerId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(customer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CustomerExists(customer.CustomerId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Customer == null)
            {
                return NotFound();
            }

            var customer = await _context.Customer
                .FirstOrDefaultAsync(m => m.CustomerId == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("DeleteConfirmed")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Customer == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Customer' is null.");
            }

            var customer = await _context.Customer.FindAsync(id);
            if (customer == null)
            {
                return NotFound();
            }

            _context.Customer.Remove(customer);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index)); // Redirect to the index page after deletion
        }

        private bool CustomerExists(int id)
        {
            return (_context.Customer?.Any(e => e.CustomerId == id)).GetValueOrDefault();
        }
    }
}

noestedmvc/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Noested.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

noestedmvc/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Noested.Models.ViewModels;

namespace Noested.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public UsersController(UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public async Task<IActionResult> Index()
        {
            var users = _userManager.Users
                .Select(u => new UserViewModel

                {
                    UserId = u.Id,
                    Email = u.Email,
                    UserName = u.UserName,

                })
                .ToList();

            var viewModel = new UserListViewModel
            {
                Users = users
            };

            return View(viewModel);
        }


        public IActionResult Register()
        {
            return RedirectToPage("/Account/Register", new { area = "Identity" });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(UserViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByIdAsync(model.UserId);

                if (user != null)
                {
                    user.Email = model.Email;
                    user.PhoneNumber = user.PhoneNumber;

                    var result = await _userManager.UpdateAsync(user);

                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }

                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);

            if (user == null)
            {
                return NotFound();
            }

            var userRoles = await _userManager.GetRolesAsync(user);
            ViewData["AllRoles"] = _roleManager.Roles.ToList();

            var viewModel = new UserViewModel
            {
                UserId = user.Id,
                Email = user.Email,
                UserName = user.UserName,
                PhoneNumber = user.PhoneNumber,
                UserRoles = userRoles.ToList(),
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditRoles(UserViewModel model)
        {
            var user = await _userManager.FindByIdAsync(model.UserId);

            if (user == null)
            {
                return NotFound();
            }

            // Remove user from existing roles
            var existingRoles = await _userManager.GetRolesAsync(user);
            await _userManager.RemoveFromRolesAsync(user, existingRoles);

            // Add user to selected roles
            var result = await _userManager.AddToRolesAsync(user, model.UserRoles);

            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }

            // If the role update fails, return to the edit roles view with the user details
            ViewData["AllRoles"] = _roleManager.Roles.ToList();
            return View("Edit", model);
        }


        [HttpGet]
        public async Task<IActionResult> Delete(string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);

            if (user == null)
            {
                return NotFound();
            }

            var viewModel = new UserViewModel
            {
                UserId = user.Id,
                UserName = user.UserName, // Optionally include the username in the confirmation view
                Email = user.Email,

            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmDelete(string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);

            if (user == null)
            {
                return NotFound();
            }

            var result = await _userManager.DeleteAsync(user);

            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }

            // If the deletion fails, return to the confirmation view with the user details
            var viewModel = new UserViewModel
            {
                UserId = user.Id,
                UserName = user.UserName,// Optionally include the username in the confirmation view
                Email = user.Email,
            };

            return View("Delete", viewModel);
        }


        [HttpGet]
        public async Task<IActionResult> Details(string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);

            if (user == null)
            {
                return NotFound();
            }

            var viewModel = new UserViewModel
            {
                UserId = user.Id,
                UserName = user.UserName,
                Email = user.Email,
                EmailConfirmed = user.EmailConfirmed,
                PhoneNumber = user.PhoneNumber,
            };

            return View(viewModel);
        }

    }

}

noestedmvc/Views/Shared/_ChecklistPartial.cshtml
@model Noested.Models.Checklist

<div asp-validation-summary="ModelOnly" class="text-danger"></div>

<!-- Product Type -->
<div class="form-group">
    <label asp-for="ProductType">Produkttype</label>
    <input asp-for="ProductType" class="form-control" />
    <span asp-validation-for="ProductType" class="text-danger"></span>
</div>

<!-- Prepared By -->
<div class="form-group">
    <label asp-for="PreparedBy">Utført av</label>
    <input asp-for="PreparedBy" class="form-control" />
</div>

<!-- Service Procedure -->
<div class="form-group">
    <label asp-for="ServiceProcedure">Prosedyre</label>
    <input asp-for="ServiceProcedure" class="form-control" />
</div>

noestedmvc/Views/Shared/_CustomerPartial.cshtml
@model Noested.Models.Customer

<div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <!-- Customer's First Name -->
<div class="form-group">
    <label asp-for="FirstName" class="control-label">Fornavn</label>
    <input asp-for="FirstName" class="form-control" />
    <span asp-validation-for="FirstName" class="text-danger"></span>
</div>
    <!-- Customer's Last Name -->
<div class="form-group">
    <label asp-for="LastName" class="control-label">Etternavn</label>
    <input asp-for="LastName" class="form-control" />
    <span asp-validation-for="LastName" class="text-danger"></span>

</div>
    <!-- Customer's Street Address -->
<div class="form-group">
    <label asp-for="Street" class="control-label">Gateadresse</label>
    <input asp-for="Street" class="form-control" />
    <span asp-validation-for="Street" class="text-danger"></span>
</div>
    <!-- Customer's Postal Code -->
<div class="form-group">
    <label asp-for="PostalCode" class="control-label">Postnummer</label>
    <input asp-for="PostalCode" class="form-control" />
    <span asp-validation-for="PostalCode" class="text-danger"></span>
</div>
    <!-- Customer's City -->
<div class="form-group">
    <label asp-for="City" class="control-label">By</label>
    <input asp-for="City" class="form-control" />
    <span asp-validation-for="City" class="text-danger"></span>
</div>
    <!-- Customer's Email -->
<div class="form-group">
    <label asp-for="Email" class="control-label">Email</label>
    <input asp-for="Email" class="form-control" />
    <span asp-validation-for="Email" class="text-danger"></span>
</div>
    <!-- Customer's Phone -->
<div class="form-group">
    <label asp-for="Phone" class="control-label">Telefon</label>
    <input asp-for="Phone" class="form-control" />
    <span asp-validation-for="Phone" class="text-danger"></span>
</div>
    <!-- Hidden value -->
    <input type="hidden" asp-for="CustomerId" value="0">

noestedmvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Noested</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.18.0/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Noested.styles.css" asp-append-version="true" />
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Account" asp-action="Login">Nøsted</a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Admin</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dashboard" asp-action="Index">Servicedesk</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ServiceOrders" asp-action="Index">Serviceordre</a>
                        </li>
                     
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customers" asp-action="Index">Kunder</a>
                        </li>

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

noestedmvc/Views/Shared/_ServiceOrderPartial.cshtml
@model Noested.Models.ServiceOrder

<!-- Existing Customer Dropdown -->
<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<div class="custom-title">Velg eksisterende kunde</div>
<div class="form-group">
    <select id="CustomerId" asp-for="CustomerId" asp-items="ViewBag.ExistingCustomers" class="form-control">
        <option value="0">-- Velg --</option>
    </select>
    <span asp-validation-for="CustomerId" class="text-danger"></span>
</div>
<!-- Garanti -->
<div class="form-group">
    <label asp-for="Warranty" class="control-label"></label>
    <select asp-for="Warranty" class="form-control">
        <option value="">Chose Condition</option>
        <option value="Full">Full</option>
        <option value="Limited">Delvis</option>
        <option value="None">Ingen</option>
    </select>
    <span asp-validation-for="Warranty" class="text-danger"></span>
</div>
<!-- Kundeavtale -->
<div class="form-group">
    <label asp-for="CustomerAgreement" class="control-label"></label>
    <input asp-for="CustomerAgreement" class="form-control" />
    <span asp-validation-for="CustomerAgreement" class="text-danger"></span>
</div>
<!-- Ordrebeskrivelse -->
<div class="form-group">
    <label asp-for="OrderDescription" class="control-label"></label>
    <input asp-for="OrderDescription" class="form-control" />
    <span asp-validation-for="OrderDescription" class="text-danger"></span>
</div>
<!-- Produktnavn -->
<div class="form-group">
    <label asp-for="ProductName" class="control-label title="Produktnavn">Produktnavn</label>
    <input asp-for="ProductName" class="form-control" required placeholder="f.eks 'IGLAND 5002 Pento TL'" />
    <span asp-validation-for="ProductName" class="text-danger"></span>
</div>
<!-- Produkttype -->
<div class="form-group">
    <label asp-for="Product" class="control-label"></label>
    <select asp-for="Product" class="form-control">
        <option value="Winch">Vinsj</option>
        <option value="TimberTrailer">Tømmertrailer</option>
        <option value="TractorShears">Traktorskjær</option>
        <option value="LiftEquip">Løfteutstyr</option>
        <option value="WoodEquip">Vedutstyr</option>
        <option value="SnowBloPlo">Snøfres/plog</option>
        <option value="SandBlaster">Sandstrøer</option>

    </select>
    <span asp-validation-for="Product" class="text-danger"></span>
</div>
<!-- Serienummer -->
<div class="form-group">
    <label asp-for="SerialNumber" class="control-label"></label>
    <input asp-for="SerialNumber" class="form-control" />
    <span asp-validation-for="SerialNumber" class="text-danger"></span>
</div>
<!-- Årsmodell -->
<div class="form-group">
    <label asp-for="ModelYear" class="control-label"></label>
    <input asp-for="ModelYear" class="form-control" />
    <span asp-validation-for="ModelYear" class="text-danger"></span>
</div>
<!-- Bruktdeler -->
<div class="form-group">
    <label asp-for="DiscardedParts" class="control-label"></label>
    <input asp-for="DiscardedParts" class="form-control" />
    <span asp-validation-for="DiscardedParts" class="text-danger"></span>
</div>
<!-- Erstatningsdeler -->
<div class="form-group">
    <label asp-for="ReplacedPartsReturned" class="control-label"></label>
    <input asp-for="ReplacedPartsReturned" class="form-control" />
    <span asp-validation-for="ReplacedPartsReturned" class="text-danger"></span>
</div>
<!-- Shipping -->
<div class="form-group">
    <label asp-for="Shipping" class="control-label"></label>
    <input asp-for="Shipping" class="form-control" />
    <span asp-validation-for="Shipping" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="IsActive" class="form-check-label"></label>
    <input asp-for="IsActive" class="form-check-input" />
</div>

noestedmvc/Views/Shared/_WinchChecklistPartial.cshtml
@model Noested.Models.WinchChecklist

<div asp-validation-summary="ModelOnly" class="text-danger"></div>

<table class="table table-bordered mb-3" id="checklistTable">
    <thead>
        <tr>
            <th>Kategorier</th>
            <th>Sjekkpunkter</th>
            <th class="checkbox-cell">OK <input type="checkbox" id="markAllOk"></th>
            <th>Bør Skiftes</th>
            <th>Defekt</th>
        </tr>
    </thead>
    <tbody>
        <!-- MechBrakes Row -->
         <tr>
            <td class="category-header" rowspan="8">Mekanisk</td>
            <td><label asp-for="MechBrakes" class="control-label"></label></td>
            <td><input asp-for="MechBrakes" type="radio" value="OK" class="form-check-input" /></td>
            <td><input asp-for="MechBrakes" type="radio" value="NeedsReplacement" class="form-check-input" /></td>
            <td><input asp-for="MechBrakes" type="radio" value="Defective" class="form-check-input" /></td>
        </tr> 

        <!-- MechDrumBearing Row -->
        <tr>
            <td><label asp-for="MechDrumBearing" class="control-label"></label></td>
            <td><input asp-for="MechDrumBearing" type="radio" value="OK" class="form-check-input" /></td>
            <td><input asp-for="MechDrumBearing" type="radio" value="NeedsReplacement" class="form-check-input" /></td>
            <td><input asp-for="MechDrumBearing" type="radio" value="Defective" class="form-check-input" /></td>
        </tr>
        <!-- MechStoragePTO Row -->
        <tr>
            <td><label asp-for="MechStoragePTO" class="control-label"></label></td>
            <td><input asp-for="MechStoragePTO" type="radio" value="OK" class="form-check-input" /></td>
            <td><input asp-for="MechStoragePTO" type="radio" value="NeedsReplacement" class="form-check-input" /></td>
            <td><input asp-for="MechStoragePTO" type="radio" value="Defective" class="form-check-input" /></td>
        </tr>
        <!-- MechWire Row -->
        <tr>
            <td><label asp-for="MechWire" class="control-label"></label></td>
            <td><input asp-for="MechWire" type="radio" value="OK" class="form-check-input" /></td>
            <td><input asp-for="MechWire" type="radio" value="NeedsReplacement" class="form-check-input" /></td>
            <td><input asp-for="MechWire" type="radio" value="Defective" class="form-check-input" /></td>
        </tr>
        <!-- MechChainTensioner Row -->
        <tr>
            <td><label asp-for="MechChainTensioner" class="control-label"></label></td>
            <td><input asp-for="MechChainTensioner" type="radio" value="OK" class="form-check-input" /></td>
            <td><input asp-for="MechChainTensioner" type="radio" value="NeedsReplacement" class="form-check-input" /></td>
            <td><input asp-for="MechChainTensioner" type="radio" value="Defective" class="form-check-input" /></td>
        </tr>
        <!-- MechPinionBearing Row -->
        <tr>
            <td><label asp-for="MechPinionBearing" class="control-label"></label></td>
            <td><input asp-for="MechPinionBearing" type="radio" value="OK" class="form-check-input" /></td>
            <td><input asp-for="MechPinionBearing" type="radio" value="NeedsReplacement" class="form-check-input" /></td>
            <td><input asp-for="MechPinionBearing" type="radio" value="Defective" class="form-check-input" /></td>
        </tr>
        <!-- MechClutch Row -->
        <tr>
            <td><label asp-for="MechClutch" class="control-label"></label></td>
            <td><input asp-for="MechClutch" type="radio" value="OK" class="form-check-input" /></td>
            <td><input asp-for="MechClutch" type="radio" value="NeedsReplacement" class="form-check-input" /></td>
            <td><input asp-for="MechClutch" type="radio" value="Defective" class="form-check-input" /></td>
        </tr>
        <!-- MechSprocketWedges Row -->
        <tr>
            <td><label asp-for="MechSprocketWedges" class="control-label"></label></td>
            <td><input asp-for="MechSprocketWedges" type="radio" value="OK" class="form-check-input" /></td>
            <td><input asp-for="MechSprocketWedges" type="radio" value="NeedsReplacement" class="form-check-input" /></td>
            <td><input asp-for="MechSprocketWedges" type="radio" value="Defective" class="form-check-input" /></td>
        </tr>
    </tbody>
    <!-- HydCylinder Row -->
    <tbody>
        <tr>
            <td class="category-header" rowspan="5">Hydralisk</td>
            <td><label asp-for="HydCylinder" class="control-label"></label></td>
            <td><input asp-for="HydCylinder" type="radio" value="OK" class="form-check-input" /></td>
            <td><input asp-for="HydCylinder" type="radio" value="NeedsReplacement" class="form-check-input" /></td>
            <td><input asp-for="HydCylinder" type="radio" value="Defective" class="form-check-input" /></td>
        </tr>
        <!-- HydHydraulicBlock Row -->
        <tr>
            <td><label asp-for="HydHydraulicBlock" class="control-label"></label></td>
            <td><input asp-for="HydHydraulicBlock" type="radio" value="OK" class="form-check-input" /></td>
            <td><input asp-for="HydHydraulicBlock" type="radio" value="NeedsReplacement" class="form-check-input" /></td>
            <td><input asp-for="HydHydraulicBlock" type="radio" value="Defective" class="form-check-input" /></td>
        </tr>
        <!-- HydTankOil Row -->
        <tr>
            <td><label asp-for="HydTankOil" class="control-label"></label></td>
            <td><input asp-for="HydTankOil" type="radio" value="OK" class="form-check-input" /></td>
            <td><input asp-for="HydTankOil" type="radio" value="NeedsReplacement" class="form-check-input" /></td>
            <td><input asp-for="HydTankOil" type="radio" value="Defective" class="form-check-input" /></td>
        </tr>
        <!-- HydGearboxOil Row -->
        <tr>
            <td><label asp-for="HydGearboxOil" class="control-label"></label></td>
            <td><input asp-for="HydGearboxOil" type="radio" value="OK" class="form-check-input" /></td>
            <td><input asp-for="HydGearboxOil" type="radio" value="NeedsReplacement" class="form-check-input" /></td>
            <td><input asp-for="HydGearboxOil" type="radio" value="Defective" class="form-check-input" /></td>
        </tr>
        <!-- HydBrakeCylinder Row -->
        <tr>
            <td><label asp-for="HydBrakeCylinder" class="control-label"></label></td>
            <td><input asp-for="HydBrakeCylinder" type="radio" value="OK" class="form-check-input" /></td>
            <td><input asp-for="HydBrakeCylinder" type="radio" value="NeedsReplacement" class="form-check-input" /></td>
            <td><input asp-for="HydBrakeCylinder" type="radio" value="Defective" class="form-check-input" /></td>
        </tr>
    </tbody>
    <!-- ElCableNetwork Row -->
    <tbody>
        <tr>
            <td class="category-header" rowspan="3">Elektrisk</td>
            <td><label asp-for="ElCableNetwork" class="control-label"></label></td>
            <td><input asp-for="ElCableNetwork" type="radio" value="OK" class="form-check-input" /></td>
            <td><input asp-for="ElCableNetwork" type="radio" value="NeedsReplacement" class="form-check-input" /></td>
            <td><input asp-for="ElCableNetwork" type="radio" value="Defective" class="form-check-input" /></td>
        </tr>
        <!-- ElRadio Row -->
        <tr>
            <td><label asp-for="ElRadio" class="control-label"></label></td>
            <td><input asp-for="ElRadio" type="radio" value="OK" class="form-check-input" /></td>
            <td><input asp-for="ElRadio" type="radio" value="NeedsReplacement" class="form-check-input" /></td>
            <td><input asp-for="ElRadio" type="radio" value="Defective" class="form-check-input" /></td>
        </tr>
        <!-- ElButtonBox Row -->
        <tr>
            <td><label asp-for="ElButtonBox" class="control-label"></label></td>
            <td><input asp-for="ElButtonBox" type="radio" value="OK" class="form-check-input" /></td>
            <td><input asp-for="ElButtonBox" type="radio" value="NeedsReplacement" class="form-check-input" /></td>
            <td><input asp-for="ElButtonBox" type="radio" value="Defective" class="form-check-input" />
        </tr>
    </tbody>
    <!-- TensionCheckBar Row -->
    <tbody>
        <tr>
            <td class="category-header" rowspan="1">Trykksettinger</td>
            <td><label asp-for="TensionCheckBar" class="control-label"></label></td>
            <td><input asp-for="TensionCheckBar" type="radio" value="OK" class="form-check-input" /></td>
            <td><input asp-for="TensionCheckBar" type="radio" value="NeedsReplacement" class="form-check-input" /></td>
            <td><input asp-for="TensionCheckBar" type="radio" value="Defective" class="form-check-input" /></td>
        </tr>
    </tbody>
    <!-- TestWinch Row -->
    <tbody>
        <tr>
            <td class="category-header" rowspan="3">Testing</td>
            <td><label asp-for="TestWinch" class="control-label"></label></td>
            <td><input asp-for="TestWinch" type="radio" value="OK" class="form-check-input" /></td>
            <td><input asp-for="TestWinch" type="radio" value="NeedsReplacement" class="form-check-input" /></td>
            <td><input asp-for="TestWinch" type="radio" value="Defective" class="form-check-input" /></td>
        </tr>
        <!-- TestTraction Row -->
        <tr>
            <td><label asp-for="TestTraction" class="control-label"></label></td>
            <td><input asp-for="TestTraction" type="radio" value="OK" class="form-check-input" /></td>
            <td><input asp-for="TestTraction" type="radio" value="NeedsReplacement" class="form-check-input" /></td>
            <td><input asp-for="TestTraction" type="radio" value="Defective" class="form-check-input" /></td>
        </tr>
        <!-- TestBrakes Row -->
        <tr>
            <td><label asp-for="TestBrakes" class="control-label"></label></td>
            <td><input asp-for="TestBrakes" type="radio" value="OK" class="form-check-input" /></td>
            <td><input asp-for="TestBrakes" type="radio" value="NeedsReplacement" class="form-check-input" /></td>
            <td><input asp-for="TestBrakes" type="radio" value="Defective" class="form-check-input" /></td>
        </tr>
    </tbody>
</table>

@section Scripts {
    <script src="/js/serviceorder.js"></script>
}